### ISSUE TITLE
Write a documentation comment for `getRandomFruit()` method

### ISSUE THREAD

**Issue by AidaIssayeva** [AidaIssayeva/android-simple-app#1]
Write a documentation comment for `getRandomFruit()` method in `MainActivity.kt` class.

To learn more about how to write a doc comment in Kotlin language, click [this link](https://kotlinlang.org/docs/coding-conventions.html#documentation-comments)

**Comment by yagmurerdogan** [comment]
I just finished this issue! Can you assign to me and check pull request 😊
